### ISSUE TITLE
RequestDeviceError on macOS Catalina

### ISSUE THREAD

**Issue by Noswad-Zip** [ElhamAryanpur/BlueEngine#8]
The camera example fails to build on macOS Catalina 10.15.7.
GPU is Intel HD Graphics 6000 1536 MB

```
   Compiling blue-engine-test v0.1.0 (/Users/[redacted]/blue-engine-test)
    Finished dev [unoptimized + debuginfo] target(s) in 5.37s
     Running `target/debug/blue-engine-test`
[2021-09-27T15:02:10Z ERROR wgpu::backend::direct] Error in Adapter::request_device: unsupported features were requested: NON_FILL_POLYGON_MODE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RequestDeviceError', /Users/[redacted]/.cargo/registry/src/github.com-1ecc6299db9ec823/blue_engine-0.1.95/src/render.rs:37:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ElhamAryanpur** [comment]
The problem appears to be the NON_FILL_POLYGON_MODE which helps in cases of wireframe and points/lines only, is only supported in DX12 and Vulkan backends, not the Metal backend which is used by OSX.

I'll find a way to fix it and update the changes.

**Comment by ElhamAryanpur** [comment]
Let me know if it still errors

**Comment by Noswad-Zip** [comment]
The error persists with blue_engine v0.1.97

**Comment by Noswad-Zip** [comment]
Modifying this function in `render.rs` stops the error and the examples compile.

```rs
fn get_render_features() -> Features {
    if std::cfg!(macos) {
        Features::empty()
    } else {
        Features::empty()
    }
}
```
I'm not sure if this is desirable, but it works! 🤷

**Comment by ElhamAryanpur** [comment]
yeah the reason for it being there is to only not support it for MacOS

I guess it couldn't detect macos. can you try running this to check if it detects or not?
```rust
fn get_render_features() -> Features {
    if std::cfg!(macos) {
        println!("Darwin");
        Features::empty()
    } else {
        println!("Not Darwin");
        Features::empty()
    }
}
```

**Comment by Noswad-Zip** [comment]
Yes. That code works!

Is there a typo in that code?

**Comment by ElhamAryanpur** [comment]
what was the output?

and no, not a typo

**Comment by ElhamAryanpur** [comment]
std::cfg!(macos) was supposed to return `true` if the code was ran on MacOS, which in turn returns empty of features since macos doesn't support that one. but it seems like it didn't return `true`.

**Comment by Noswad-Zip** [comment]
```
   Compiling blue_engine v0.1.97 (/Users/[redacted]/BlueEngine)
warning: unused import: `header::{}`
 --> src/utils/text.rs:7:13
  |
7 | use crate::{header::{}, objects};
  |             ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `position`
  --> src/utils/text.rs:44:9
   |
44 |         position: (u8, u8),
   |         ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_position`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `blue_engine` (lib) generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 9.64s
     Running `target/debug/examples/rotate_around`
Not Darwin
[2021-09-28T19:10:39Z ERROR wgpu::backend::direct] Error in Adapter::request_device: unsupported features were requested: NON_FILL_POLYGON_MODE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RequestDeviceError', src/render.rs:52:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dawson-Morrison:BlueEngine s1963847596$ cargo run --example rotate_around
   Compiling blue_engine v0.1.97 (/Users/[redacted]/BlueEngine)
warning: unused import: `header::{}`
 --> src/utils/text.rs:7:13
  |
7 | use crate::{header::{}, objects};
  |             ^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused variable: `position`
  --> src/utils/text.rs:44:9
   |
44 |         position: (u8, u8),
   |         ^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_position`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `blue_engine` (lib) generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 7.85s
     Running `target/debug/examples/rotate_around`
Not Darwin
```

**Comment by ElhamAryanpur** [comment]
yep... MacOS wasn't detected...

**Comment by ElhamAryanpur** [comment]
@Noswad-Zip try to replace that function with this
```rust
#[cfg(not(target_feature = "NON_FILL_POLYGON_MODE"))]
fn get_render_features() -> Features {
    Features::empty()
}
#[cfg(target_feature = "NON_FILL_POLYGON_MODE")]
fn get_render_features() -> Features {
    Features::NON_FILL_POLYGON_MODE
}
```

**Comment by ElhamAryanpur** [comment]
this time it'll only return that feature if the NON_FILL_POLYGON_MODE feature is enabled through cargo.toml 😄

**Comment by Noswad-Zip** [comment]
This works!

**Comment by ElhamAryanpur** [comment]
Awesome!
